DATAACCESS: Write AdminRepository Create method
eclouz/eclo-webapi pull request #50
Opened 2023-08-08 05:14 UTC by javohirtohirovich

2023-08-08 07:17 UTC, ShohruhUzDev requested changes

2023-08-08 07:17 UTC, ShohruhUzDev commented on src/Eclo.DataAccess/Repositories/Admins/AdminRepository.cs
> +                         "@Region, @District, @Address, @CreatedAt, @UpdatedAt);";
har bir yangi qator tashlanganda tab tashlanishi kerak

2023-08-09 04:13 UTC, Maxsetovich approved these changes
Completed AdminRepository

2023-08-09 04:27 UTC, Maxsetovich approved these changes
fixes are resolved

2023-08-09 04:27 UTC, Maxsetovich approved these changes
fixes are resolved

2023-08-09 04:28 UTC, merged